config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  get '/about', to: 'pages#about_us', as: :about
  get '/impressum', to: 'pages#impressum', as: :impressum
  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/terms_of_use', to: 'pages#terms_of_use', as: :terms_of_use
  get '/privacy/facebook', to: 'pages#facebook_privacy', as: :facebook_privacy
  get '/admin/dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/users', to: 'pages#users', as: :users

  resources :categories
  resources :events, except: :index do
    resources :user_favourites, only: [:create, :destroy]
  end
end

app/views/shared/_admin-option.html.erb
<% if large %>
<div class="option option-large">
<% else %>
<div class="option">
<% end %>
  <h2><%= option %></h2>
</div>

app/views/shared/_bubble.html.erb
<svg width="200" height="171" viewBox="0 0 200 171" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M91.4959 0.00477214C108.926 0.331614 120.278 17.3733 134.508 27.444C148.98 37.6859 165.379 44.7575 175.399 59.3837C188.245 78.134 204.18 99.4451 198.995 121.574C193.777 143.848 171.415 158.984 150.112 167.323C131.424 174.638 111.434 165.929 91.4959 163.654C74.3872 161.702 56.224 164.46 41.8549 154.971C27.1598 145.266 19.98 128.35 13.3392 112.04C6.1847 94.4687 -4.72568 75.2929 2.22563 57.64C9.13352 40.0973 31.4558 36.0349 47.2952 25.8086C61.9876 16.3229 74.0105 -0.323107 91.4959 0.00477214Z" fill="#B3FDB1"/>
</svg>

app/views/shared/_category-card-mobile.html.erb
<div class="category-card-mobile" style="background-image: url('<%= cl_image_path category.photo.key, height: 600, width: 800, crop: :fill %>')">
  <div class="gradient">
    <h4 class="category-card-text"><%= category.name %></h4>
  </div>
</div>

app/views/shared/_category-card.html.erb
<div class="category-card" style="background-image: url('<%= cl_image_path category.photo.key, height: 600, width: 800, crop: :fill %>')">
  <div class="gradient">
    <h4 class="category-card-text"><%= category.name %></h4>
  </div>
</div>

app/views/shared/_dynamic-header.html.erb
<% letter_count = @event.name.length %>
<% font_size = letter_count > 20 ? (2 - ((letter_count - 20) / 3) / 10.0) : 2 %>

<% if user_signed_in? %>
  <% if current_user.admin %>
    <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half" style="font-size: <%= font_size %>em"><%= @event.name %> <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_event_path(@event) %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, event_path(@event), method: :delete, data: {confirm: "Are you sure you want to delete this event?"} %></h2>
  <% else %>
    <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half" style="font-size: <%=  %>"><%= @event.name %></h2>
  <% end %>
<% else %>
  <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half" style="font-size: <%=  %>"><%= @event.name %></h2>
<% end %>

app/views/shared/_event-card-slider.html.erb
<div class="event-card-slider">
  <%= cl_image_tag event.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="event-card-content">
    <h2><%= event.name %></h2>
    <p><%= event.description.truncate(70) %></p>
  </div>
</div>

app/views/shared/_event-card.html.erb
<div class="event-card">
  <%= cl_image_tag event.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="event-card-content">
    <h2><%= event.name %></h2>
    <p><%= event.description.truncate(70) %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wrapper">
  <%= link_to (render 'shared/logo'), root_path %>
  <h3><%= link_to 'Kategorien', categories_path %></h3>
  <h3>Live Streams</h3>
  <h3><%= link_to 'Über uns', about_path %></h3>
  <% if user_signed_in? %>
    <% if current_user.photo.attached? %>
      <%= link_to (cl_image_tag current_user.photo.key, height: 100, width: 100, crop: :fill, class: "avatar-round"), edit_user_registration_path %>
    <% else %>
      <% avatar_url = current_user.facebook_picture_url || "https://www.hilfsgemeinschaft.at/profiles/hilfsgemeinschaft_profile/themes/custom/hilfsgemeinschaft_zomg/images/user-picture-default.png" %>
      <%= link_to (image_tag avatar_url, class: "avatar-round"), edit_user_registration_path %>
    <% end %>
  <% else %>
    <h3><%= link_to "Login", new_user_session_path %></h3>
  <% end %>
</div>

app/views/shared/_navbar_mobile.html.erb
<div class="navbar-wrapper">
  <div onclick="toggleSidebar()" id="toggle-sidebar" class="hamburger-icon">
    <div class="hamburger-line hamburger-line-one"></div>
    <div class="hamburger-line hamburger-line-two"></div>
  </div>
  <%= link_to (render 'shared/mobile-logo'), root_path %>
  <% if user_signed_in? %>
    <div class="avatar-wrapper">
      <% if current_user.photo.attached? %>
        <%= link_to (cl_image_tag current_user.photo.key, height: 100, width: 100, crop: :fill, class: "avatar-round"), edit_user_registration_path %>
      <% else %>
        <% avatar_url = current_user.facebook_picture_url || "https://www.hilfsgemeinschaft.at/profiles/hilfsgemeinschaft_profile/themes/custom/hilfsgemeinschaft_zomg/images/user-picture-default.png" %>
        <%= link_to (image_tag avatar_url, class: "avatar-round"), edit_user_registration_path %>
      <% end %>
    </div>
  <% else %>
    <h5><%= link_to "Login", new_user_session_path %></h5>
  <% end %>
</div>

<div class="sidebar">
  <%= render 'shared/sidebar' %>
</div>

<script>
  function toggleSidebar() {
    document.querySelector('.sidebar').classList.toggle('show');
    document.querySelector('.hamburger-icon').classList.toggle('hamburger-x');
    document.querySelector('body').classList.toggle('stop-scrolling');
    document.querySelector('#body-content').classList.toggle('shift-content');
    document.querySelector('.navbar-wrapper').classList.toggle('shift-content');
  }
</script>

app/views/shared/_sidebar.html.erb
<h4><%= link_to "Start", root_path %></h4>
<div onclick="toggleCategories()" id="toggle-categories">
  <h4>Kategorien <i class="fas fa-sort-down"></i></h4>
</div>
<div class="category-list">
  <% Category.order(:name).each do |category| %>
    <h4><%= link_to category.name, category_path(category) %></h4>
  <% end %>
</div>
<h4><%= link_to "Über uns", about_path %></h4>
<h5><%= link_to "Impressum", impressum_path %></h5>
<h5><%= link_to "Datenschutz", privacy_path %></h5>

<script>
  function toggleCategories() {
    document.querySelector('.category-list').classList.toggle('show');
    document.querySelector('.fa-sort-down').classList.toggle('rotate');
  }
</script>