config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  get '/about', to: 'pages#about_us', as: :about
  get '/impressum', to: 'pages#impressum', as: :impressum
  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/terms_of_use', to: 'pages#terms_of_use', as: :terms_of_use
  get '/privacy/facebook', to: 'pages#facebook_privacy', as: :facebook_privacy
  get '/admin/dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/users', to: 'pages#users', as: :users

  resources :categories
  resources :events, except: :index do
    resources :user_favourites, only: [:create, :destroy]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  has_many :user_favourites, dependent: :destroy
  has_one_attached :photo

  validates_presence_of :name, message: 'Please enter a name'
  validates_presence_of :description, message: 'Please enter a description'
  validates_presence_of :category_id, message: 'Please select a category'
  validate :photo_is_attached

  def photo_is_attached
    errors.add(:photo, "Please upload a picture") unless photo.attached?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  def show
    category = @event.category
    category.count += 1
    category.save
    @event.count += 1
    @event.save
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    category = @event.category
    @event.photo.purge
    @event.destroy
    redirect_to category_path(category)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :category_id, :amazon_link, :photo)
  end

  def check_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin
    else
      redirect_to root_path
    end
  end
end

app/views/events/edit.html.erb
<div class="container spacing-top-1">
  <h2 class="about-header">Edit Event</h2>
  <%= simple_form_for(@event) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :category_id, collection: Category.all %>
    <%= f.input :amazon_link %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex justify-content-center mb-5">
      <%= f.button :submit, class: "button-blue" %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container spacing-top-1">
  <h2 class="about-header">New Event</h2>
  <%= simple_form_for(@event) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :category_id, collection: Category.all %>
    <%= f.input :amazon_link %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex justify-content-center mb-5">
      <%= f.button :submit, class: "button-blue" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="gradient" style="position: relative;">
    <% if mobile_device == "mobile" %>
      <%= cl_image_tag @event.photo.key, height: 300, width: 400, crop: :fill, class: "image-full-width-30" %>
    <% else %>
      <%= cl_image_tag @event.photo.key, height: 600, width: 800, crop: :fill, class: "image-full-width-50" %>
    <% end %>
    <% if UserFavourite.where(user: current_user).find_by_event_id(@event.id) %>
      <% bookmark = UserFavourite.where(user: current_user).find_by_event_id(@event.id) %>
      <%= link_to '<i class="fas fa-heart"></i>'.html_safe, event_user_favourite_path(@event, bookmark), method: :delete, remote: true, class: "bookmark-icon bookmarked data-event-#{@event.id}" %>
    <% else %>
      <%= link_to '<i class="far fa-heart"></i>'.html_safe, event_user_favourites_path(@event), method: :post, remote: true, class: "bookmark-icon data-event-#{@event.id}" %>
    <% end %>
  </div>


  <div class="border-bottom-blue">
    <%= render 'shared/dynamic-header' %>
  </div>

  <p class="spacing-top-1 padding-bottom-1 padding-left-1 padding-right-1 border-bottom-blue"><%= @event.description %></p>

  <h4 class="about-header">Zur Seite: <a href="<%= @event.amazon_link %>" target="_blank"><i class="fas fa-external-link-alt"></i></a></h4>
</div>