config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  get '/about', to: 'pages#about_us', as: :about
  get '/impressum', to: 'pages#impressum', as: :impressum
  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/terms_of_use', to: 'pages#terms_of_use', as: :terms_of_use
  get '/privacy/facebook', to: 'pages#facebook_privacy', as: :facebook_privacy
  get '/admin/dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/users', to: 'pages#users', as: :users

  resources :categories
  resources :events, except: :index do
    resources :user_favourites, only: [:create, :destroy]
  end
end

app/views/pages/_home_desktop.html.erb
<div class="banner-caroussel">
  <% Event.order(count: :desc).first(5).each do |event| %>
    <div class="banner-content">
      <div class="banner-image" style="background-image: url('<%= cl_image_path event.photo.key, height: 400, width: 600, crop: :fill %>')"></div>
      <%= link_to "<div class='banner-info'><h1>#{event.name}</h1><p>#{event.description.truncate(200)}</p></div>".html_safe, event_path(event) %>
    </div>
  <% end %>
</div>

<div class="home-banner">
  <div class="logo-tagline">
    <h2>entertainly</h2>
    <h5>Insert tagline here</h5>
  </div>

  <div class="info-text">
    <% if user_signed_in? %>
      <% if current_user.admin %>
        <a href="/admin/dashboard">
          <h3 class="highlighted-header">Hier gehts zur Admin Seite</h3>
          <p>Dort kannst du Events und Kategorien hinzufügen</p>
        </a>
      <% else %>
        <h3 class="highlighted-header">Was uns antreibt</h3>
        <p>Wir wollen die Einsamkeit und Langeweile vertreiben. Vergnügt euch mit entertainly! Die Seite wird ständig weiterentwickelt.</p>
      <% end %>
    <% else %>
      <h3 class="highlighted-header">Was uns antreibt</h3>
      <p>Wir wollen die Einsamkeit und Langeweile vertreiben. Vergnügt euch mit entertainly! Die Seite wird ständig weiterentwickelt.</p>
    <% end %>
  </div>
</div>

<div class="categories">
  <h2 class="highlighted-header">Top Kategorien</h2>
  <div class="category-cards">
    <% Category.order(count: :desc).first(6).each do |category| %>
      <%= link_to (render 'shared/category-card', category: category), category_path(category) %>
    <% end %>
  </div>
</div>

<div class="categories">
  <h2 class="highlighted-header">Deine Favoriten</h2>
  <% if user_signed_in? %>
    <% if current_user.events.count > 0 %>
      <div class="category-cards">
        <% current_user.events.order(count: :desc).each do |event| %>
          <%= link_to (render 'shared/category-card', category: event), event_path(event) %>
        <% end %>
      </div>
    <% else %>
      <div class="info-text">
        <h5>Du hast noch keine Favoriten 🤭</h5>
        <p>Klicke einfach bei Artikeln, die du später nochmal anschauen willst auf das <i class="far fa-heart"></i>, um sie deiner Liste hinzuzufügen.</p>
      </div>
    <% end %>
  <% else %>
    <div class="info-text">
      <h5>Log dich hier ein, um deine Favoriten zu sehen</h5>
      <h5><%= link_to "Login", new_user_session_path, class: 'button button-blue' %></h5>
    </div>
  <% end %>
</div>

app/views/pages/_home_mobile.html.erb
<% top_event = Event.order(count: :desc).first %>
<% letter_count = top_event.name.length %>
<% font_size = letter_count > 20 ? (1.75 - ((letter_count - 20) / 3) / 10.0) : 1.75 %>
<div class="banner-content-mobile">
  <div class="banner-image" style="background-image: url('<%= cl_image_path top_event.photo.key, height: 600, width: 800, crop: :fill %>')"></div>
  <div class="banner-info">
    <%= link_to "<h3 style='font-size: #{font_size}em'>#{top_event.name}</h3><p>#{top_event.description.truncate(45)}</p>".html_safe, event_path(top_event) %>
  </div>
</div>

<div class="home-banner-mobile">
  <div class="info-text">
    <% if user_signed_in? %>
      <% if current_user.admin %>
        <a href="/admin/dashboard">
          <h3 class="highlighted-header">Hier gehts zur Admin Seite</h3>
          <p>Dort kannst du Events und Kategorien hinzufügen</p>
        </a>
      <% else %>
        <h3 class="highlighted-header">Was uns antreibt</h3>
        <p>Wir wollen die Einsamkeit und Langeweile vertreiben. Vergnügt euch mit entertainly! Die Seite wird ständig weiterentwickelt.</p>
      <% end %>
    <% else %>
      <h3 class="highlighted-header">Was uns antreibt</h3>
      <p>Wir wollen die Einsamkeit und Langeweile vertreiben. Vergnügt euch mit entertainly! Die Seite wird ständig weiterentwickelt.</p>
    <% end %>
  </div>
</div>

<div class="mobile-slider">
  <h4 class="highlighted-header">Top Kategorien</h4>
  <div class="slider-cards">
    <% Category.order(count: :desc).first(6).each do |category| %>
      <%= link_to (render 'shared/category-card-mobile', category: category), category_path(category) %>
    <% end %>
    <a href="/categories">
      <div class="category-card-mobile">
        <div class="gradient">
          <h4 class="category-card-text">All Categories</h4>
        </div>
      </div>
    </a>
  </div>
</div>

<div class="link-center">
  <%= link_to "Hier gehts zu allen Kategorien", categories_path, class: 'highlighted-header' %>
</div>

<div class="mobile-slider">
  <h4 class="highlighted-header">Deine Favoriten</h4>
  <% if user_signed_in? %>
    <% if current_user.events.count > 0 %>
      <div class="slider-cards">
        <% current_user.events.order(count: :desc).each do |event| %>
          <%= link_to (render 'shared/category-card-mobile', category: event), event_path(event) %>
        <% end %>
      </div>
    <% else %>
      <div class="info-text">
        <h5>Du hast noch keine Favoriten 🤭</h5>
        <p>Klicke einfach bei Artikeln, die du später nochmal anschauen willst auf das <i class="far fa-heart"></i>, um sie deiner Liste hinzuzufügen.</p>
      </div>
    <% end %>
  <% else %>
    <div class="info-text">
      <h5>Log dich hier ein, um deine Favoriten zu sehen</h5>
      <h5><%= link_to "Login", new_user_session_path, class: 'button button-blue' %></h5>
    </div>
  <% end %>
</div>

<div class="mobile-slider border-top-blue">
  <h4 class="highlighted-header">Highlights</h4>
  <div class="slider-cards">
    <% Event.order(count: :desc).first(6).each do |event| %>
      <%= link_to (render 'shared/category-card-mobile', category: event), event_path(event) %>
    <% end %>
  </div>
</div>

app/views/pages/about_us.html.erb
<h1 class="about-header">Über uns</h1>

<div class="bubble-section">
  <%= render 'shared/bubble' %>
  <div class="bubble-section-content">
    <h1>Was uns antreibt</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus assumenda adipisci, expedita alias corrupti incidunt magnam soluta iste ducimus. Molestias provident ea delectus, esse sapiente commodi deserunt, laborum nihil vel!</p>
  </div>
</div>

<div class="bubble-section">
  <%= render 'shared/bubble' %>
  <div class="bubble-section-content">
    <h1>Wer wir sind</h1>
    <div class="team-pictures">

    </div>
  </div>
</div>

app/views/pages/admin_dashboard.html.erb
<div class="container">
  <h2 class="about-header">Hello <%= current_user.first_name %></h2>

  <div class="admin-options border-bottom-blue">
    <%= link_to (render 'shared/admin-option', option: 'Add Event', large: false), new_event_path %>
    <%= link_to (render 'shared/admin-option', option: 'Add Category', large: false), new_category_path %>
    <%= link_to (render 'shared/admin-option', option: 'All Users', large: true), users_path %>
  </div>

  <div class="admin-stats">
    <h2 class="highlighted-header">Statistics</h2>
    <div class="inline-stats border-bottom-blue">
      <h3>Total Users:</h3>
      <h3><%= User.count %></h3>
    </div>

    <div class="inline-stats border-bottom-blue">
      <h3>New Users this Week:</h3>
      <h3><%= User.where("created_at > ?", Date.today - 7).count %></h3>
    </div>

    <div class="inline-stats border-bottom-blue">
      <h3>New Users this Month:</h3>
      <h3><%= User.where("created_at > ?", Date.today - 31).count %></h3>
    </div>

    <div class="inline-stats border-bottom-blue">
      <h3>Unique Visitors:</h3>
      <h3><%= Visitor.count %></h3>
    </div>

    <div class="inline-stats border-bottom-blue">
      <h3>Total page visits:</h3>
      <% visits = 0 %>
      <% Visitor.all.each do |visitor| %>
        <% visits += visitor.count %>
      <% end %>
      <h3><%= visits %></h3>
    </div>

    <div class="list-stats border-bottom-blue">
      <h3>Trending Categories:</h3>
      <% Category.order(count: :desc).first(5).each do |category| %>
        <div class="list-item">
          <h3><%= category.name %></h3>
          <h3><%= category.count %></h3>
        </div>
      <% end %>
    </div>

    <div class="list-stats border-bottom-blue">
      <h3>Trending Events:</h3>
      <% Event.order(count: :desc).first(5).each do |event| %>
        <div class="list-item">
          <h3><%= event.name %></h3>
          <h3><%= event.count %></h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/facebook_privacy.html.erb
<h1 class="about-header">Datenschutz</h1>

<div class="container">
  <p>
    Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert.
    Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem "Like-Button" ("Gefällt mir“) auf unserer Seite.
    Eine Übersicht über die Facebook-Plugins finden Sie hier: <a href="http://developers.facebook.com/docs/plugins/">http://developers.facebook.com/docs/plugins/</a>
    Wenn Sie unsere Seiten besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt.
    Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben.
    Wenn Sie den Facebook „Like-Button“ anklicken während Sie in Ihrem Facebook-Account eingeloggt sind, können Sie die Inhalte unserer Seiten auf Ihrem Facebook-Profil verlinken.
    Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen.
    Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten.
    Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von facebook unter <a href="https://de-de.facebook.com/policy.php">https://de-de.facebook.com/policy.php</a>
    Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.
  </p>
</div>

app/views/pages/home.html.erb
<% if mobile_device == "mobile" %>
  <%= render 'home_mobile' %>
<% else %>
  <%= render 'home_desktop' %>
<% end %>

app/views/pages/impressum.html.erb
<div class="text-center-screen">
  <h2 class="about-header">Impressum</h2>

  <h4>
    Lukas Beckmann<br>
    Großenbuschstr. 93<br>
    53757 Sankt Augustin<br>

    <a href="mailto:hallo@entertainly.de">hallo@entertainly.de</a><br>
    +49 2241 2619031<br>
  </h4>

  <h2 class="about-header">entertainly</h2>
  <h4><a href="mailto:presse@entertainly.de">presse@entertainly.de</a></h4>
</div>

app/views/pages/terms_of_use.html.erb
<div class="spacing-left-1 spacing-right-1">
  <h2 class="about-header">Nutzungsbedingungen</h2>
  <p>
    Nutzungsbedingungen<br>
    Version: 1 Stand: 23.03.2020<br>
    <br>
    Willkommen bei "entertainly"! Die nachfolgenden Nutzungsbedingungen regeln die kostenlose Nutzung von "entertainly" über das Internet, mobile Dienste, Apps, andere Domains oder Kommunikationswege:<br>
    <br>
    1. Nutzung von "entertainly"<br>
    <br>
    Bei der Nutzung von "entertainly" verpflichtest du dich, die geltenden gesetzlichen Vorschriften zu beachten. Das betrifft z.B. den Schutz der Persönlichkeitsrechte anderer Nutzer oder das Urheberrecht an Fotos.<br>
    "entertainly" ist kostenlos. Wir übernehmen keine Garantie oder Gewähr für Informationen auf "entertainly", für Inhalte anderer Nutzer oder für eine bestimmte Verfügbarkeit oder Funktionalität von "entertainly".<br>
    Wir behalten uns aber vor, sowohl Nutzer als auch ihre Inhalte jederzeit zu sperren oder zu löschen. Eine Löschung und / oder Sperrung aus anderen Gründen behalten wir uns ausdrücklich vor. Diese Gründe liegen in unserem Ermessen. Wir sind nicht dazu verpflichtet, die Nutzer über diese Gründe zu informieren.<br>
    <br>
    An der Struktur und den Funktionalitäten von "entertainly" sowie deren Bezeichnungen (z.B. bei Gruppen, Events) und den Datenbanken von "entertainly" behalten bzw. erwerben bei Fortentwicklung nur wir die ausschließlichen und unbeschränkten Rechte.<br>
    <br>
    2. Änderung der Nutzungsbedingungen<br>
    <br>
    Mit deiner Zustimmung oder wenn deine Zustimmung nach den folgenden Bestimmungen als erteilt gilt, können wir die mit dir vereinbarten Nutzungsbedingungen anpassen (z.B. bei Einführung neuer Funktionen).<br>
    Wenn wir die Nutzungsbedingungen ändern möchten, teilen wir dir dies in Textform (also z.B. per E-Mail) mit. Widersprichst du nicht innerhalb von sechs Wochen nach Zugang dieser Mitteilung in Textform, gilt deine Zustimmung zur Änderung als erteilt und die Änderungen werden zum angekündigten Zeitpunkt wirksam. Auf diese Folge weisen wir dich in der Änderungsmitteilung besonders hin. <br>
    <br>
    3. Datenschutz<br>
    <br>
    "entertainly" unterliegt deutschem und europäischem Datenschutzrecht. Informationen zur Erhebung, Verarbeitung und Nutzung personenbezogener Daten findest du in unserer Datenschutzerklärung.<br>
    <br>
    4. Alternative Streitbeilegung gemäß Verbraucherstreitbeilegungsgesetz<br>
    <br>
    Wir weisen dich darauf hin, dass wir nicht bereit und nicht verpflichtet sind, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.<br>
    <br>
    5. Anwendbares Recht<br>
    <br>
    Es gilt deutsches Recht.<br>
  </p>

</div>

app/views/pages/users.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="user-card">
      <% if user.photo.attached? %>
        <%= cl_image_tag user.photo.key, height: 100, width: 100, crop: :fill, class: "avatar-round" %>
      <% else %>
        <% avatar_url = user.facebook_picture_url || "https://www.hilfsgemeinschaft.at/profiles/hilfsgemeinschaft_profile/themes/custom/hilfsgemeinschaft_zomg/images/user-picture-default.png" %>
        <%= image_tag avatar_url, class: "avatar-round" %>
      <% end %>
      <h4><%= user.first_name %> <%= user.last_name %></h4>
      <p><%= user.email %></p>
    </div>
  <% end %>
</div>