config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  get '/about', to: 'pages#about_us', as: :about
  get '/impressum', to: 'pages#impressum', as: :impressum
  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/terms_of_use', to: 'pages#terms_of_use', as: :terms_of_use
  get '/privacy/facebook', to: 'pages#facebook_privacy', as: :facebook_privacy
  get '/admin/dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/users', to: 'pages#users', as: :users

  resources :categories
  resources :events, except: :index do
    resources :user_favourites, only: [:create, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events, dependent: :destroy
  has_one_attached :photo

  validates_presence_of :name, message: 'Please enter a name'
  validate :photo_is_attached

  def photo_is_attached
    errors.add(:photo, "Please upload a picture") unless photo.attached?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Category.order(:name)
  end

  def show
    @category.count += 2
    @category.save
    @events = @category.events.order(count: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  def destroy
    @category.photo.purge
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :photo)
  end

  def check_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin
    else
      redirect_to root_path
    end
  end
end

app/views/categories/edit.html.erb
<div class="container spacing-top-1">
  <h2 class="about-header">Edit Category</h2>
  <%= simple_form_for(@category) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex justify-content-center mb-5">
      <%= f.button :submit, class: "button-blue" %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="categories">
  <h2 class="highlighted-header">Alle Kategorien</h2>
  <div class="category-cards">
    <% @categories.each do |category| %>
      <%= link_to (render 'shared/category-card', category: category), category_path(category) %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container spacing-top-1">
  <h2 class="about-header">New Category</h2>
  <%= simple_form_for(@category) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex justify-content-center mb-5">
      <%= f.button :submit, class: "button-blue" %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<% if mobile_device == "mobile" %>
  <%= cl_image_tag @category.photo.key, height: 300, width: 400, crop: :fill, class: "image-full-width-30" %>
<% else %>
  <div class="container">
  <%= cl_image_tag @category.photo.key, height: 600, width: 800, crop: :fill, class: "image-full-width-50" %>
<% end %>

<div class="border-bottom-blue">
  <% if user_signed_in? %>
    <% if current_user.admin %>
      <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half"><%= @category.name %> <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_category_path(@category) %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, category_path(@category), method: :delete, data: {confirm: "Are you sure you want to delete this category? All events (#{@events.count} in total) will be deleted as well!"} %></h2>
    <% else %>
      <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half"><%= @category.name %></h2>
    <% end %>
  <% else %>
    <h2 class="highlighted-header spacing-left-half spacing-top-half spacing-bottom-half"><%= @category.name %></h2>
  <% end %>
</div>

<div class="highlighted-header spacing-top-1 spacing-left-1">
  <h2>Aktuell beliebt</h2>
</div>

<% if mobile_device == "mobile" %>
  <div class="event-slider-mobile border-bottom-blue">
    <% if @events.count > 0 %>
      <% @events.first(5).each do |event| %>
        <%= link_to (render 'shared/event-card-slider', event: event), event_path(event) %>
      <% end %>
    <% else %>
      <h2 class="about-header">Coming soon</h2>
    <% end %>
  </div>
<% else %>
  <div class="categories">
    <% if @events.count > 0 %>
      <div class="category-cards">
        <% @events.first(5).each do |event| %>
          <%= link_to (render 'shared/event-card', event: event), event_path(event) %>
        <% end %>
      </div>
    <% else %>
      <h2 class="about-header">Coming soon</h2>
    <% end %>
  </div>
<% end %>

<% if user_signed_in? %>
  <% if current_user.admin %>
    <h5><%= link_to "Add Event", new_event_path, class: 'button button-blue' %></h5>
  <% end %>
<% end %>

<% if @events.count > 5 %>
  <div class="highlighted-header spacing-top-1 spacing-left-1">
    <h2>Alle <%= @category.name %></h2>
  </div>

  <div class="event-grid">
    <% @events[5..].each do |event| %>
      <%= link_to (render 'shared/event-card', event: event), event_path(event) %>
    <% end %>
  </div>
<% end %>

<% unless mobile_device == "mobile" %>
  </div>
<% end %>